//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app4client3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateOfTickets { get; set; }
        public string Naimenovanie { get; set; }
        public string Deskription { get; set; }
        public string Status { get; set; }
        public int ClientID { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
